Added pre-commit hook
TreyWW/MyFinances pull request #257
Opened 2024-03-31 21:55 UTC by introkun

## Description

# Checklist

- [ ] Ran the [Black Formatter](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) and
  [djLint-er](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) on any new code
  (checks
  will
  fail without)
- [ ] Made any changes or additions to the documentation _where required_
- [ ] Changes generate no new warnings/errors
- [ ] New and existing [unit tests](https://docs.strelix.org/MyFinances/#/how-to-contribute?id=test-and-lint) pass locally with my
  changes

## What type of PR is this?

- ✨ Feature
- 🐛 Bug Fix
- 🚨 Breaking Change
- ♻️ Code Refactor
- 📝 Documentation Update

## Added/updated tests?

- 👍 yes
- 🙅 no, because they aren't needed
- 🙋 no, because **I need help**

## Related PRs, Issues etc
- Related Issue #
- Closes #

2024-04-02 00:30 UTC, introkun commented
Done @TreyWW

2024-04-02 00:58 UTC, introkun commented
typos error is fixed in https://github.com/TreyWW/MyFinances/pull/272

2024-04-03 02:09 UTC, introkun commented
ready @TreyWW

2024-04-03 10:16 UTC, TreyWW requested changes

2024-04-03 10:16 UTC, TreyWW commented on README.md
> +    - view any changed pages in browser (`http://127.0.0.1:800`) and make sure the changes work as expected
Should be 8000

2024-04-03 10:16 UTC, TreyWW commented on .pre-commit-config.yaml
> +    -   id: requirements-txt-fixer
We technically don't need requirements.txt right, since we use poetry

2024-04-03 10:16 UTC, TreyWW commented on .pre-commit-config.yaml
> +    -   id: add-trailing-comma
Arent trailing commas normally the most annoying and worst style? I get it for tulples where they're needed but for lists etc?

2024-04-03 20:42 UTC, introkun commented
fixed review notes @TreyWW

2024-04-03 20:46 UTC, introkun commented
ready for review

2024-04-04 15:48 UTC, TreyWW approved these changes

2024-04-04 16:27 UTC, merged